;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-semi&comma
        forward-symbol
        smart-tab
        ))

(setq mc/cmds-to-run-once
      '(
        backward-symbol
        c-electric-paren
        c-electric-slash
        smex
        ))
